# Generated by Django 5.2.4 on 2025-07-28 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name="Item's name")),
                ('description', models.TextField(max_length=4096, verbose_name="Item's description")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Item's price")),
            ],
        ),
    ]
