# Generated by Django 5.2.4 on 2025-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_discount_tax_item_currency_order_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Discount Code'),
        ),
    ]
