services:
  web:
    build:
      context: smt/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./smt:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: CMD-SHELL pg_isready -U $POSTGRES_USER
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  postgres_data: